# --- HOME ---
name: The Insight Group
bio: Professional mentorship at Northwestern University

# @Henry fill this in
home_bio: Impact through insight is our ethos

# --- IMAGES ---
# if it's an external image, update below for true
# better with square images
external-image: false
logo_no_text: assets/images/logo-no-text.jpg
logo: assets/images/logo.jpg
kellogg: assets/images/kellogg.jpg

# --- BASE STUFF ---
# keep this HTTPS
url: https://www.theinsightgroup.org
permalink: /:title/
facebook: NUInsightGroup
linkedin: company/v-insight-group-northwestern
email: henry@theinsightgroup.org
# spotify: myspotify

# --- ABOUT ---
about:
  history: The Insight Group was founded in 2008 by a small group of passionate undergraduates for the purpose of peer-guided career advancement.
  now: Since then, we have grown quite a bit, but our core mission has stayed the same. It is our belief that career advancement is a stressful and often overwhelming process for our peers at Northwestern University because existing institutions neglect to educate and prepare on an individual level. 
  mission: Our core mission is to serve as an all-purpose career guide for the students of our Insight community, and of the broader Northwestern University community. It has been our priviledge over the last decade plus to learn and grow alongside such remarkable and distinguished communities of people.
  henry_quote: We at The Insight Group have always been, and will always be fueled by our potential for impact. Every student in our community should feel supported by our extensive network of mentors, and encouraged to pursue their passions. – Henry Forcier, Class of '21

# --- EVENTS ---
events:
  paragraph: Our annual Consulting vs. Investment Banking event will occur sometime in November, however dates have not yet been finalized.
  first:
    title:
    description:
    img:
  second:
    title:
    description:
    img:

# --- APPLY ---
apply:
  paragraph: Applications will open soon for our newest class of general members! Check back in early November.
  link:
  # @Henry put link here for applications

# --- DONATE ---
donate: true

# --- ALUMNI ---
alumni:
  paragraph: Our alumni are a testament to the impact we have created for Northwestern University undergraduates since 2008. This page highlights the current Advisory Board of The Insight Group, which is a select group of alumni committed to the continued service of our mission and the development of our Executive Board. 
  first:
    name: Blair Kessler
    bio: Founder of The Insight Group
    work: Engagement Manager at McKinsey & Company
    img: assets/images/logo.jpg
  second:
    name: Tanisha Patni
    bio: Former President of The Insight Group
    work: Corporate Finance Senior Analyst at Zynga
    img: assets/images/logo.jpg
  third:
    name: Raghav Kapur
    bio: Former President of The Insight Group
    work: Associate at PwC Strategy&
    img: assets/images/logo.jpg
  fourth:
    name: Michael Oppenheim
    bio: Former President of The Insight Group
    work: Business Analyst at The Cambridge Group
    img: assets/images/logo.jpg
  fifth:
    name: Michelle Lu
    bio: Former Director of Programming
    work: Associate at PwC Strategy&
    img: assets/images/logo.jpg
  sixth:
    name: Eshawn Sharma
    bio: Former President of The Insight Group
    work: Associate Consultant at Bain & Company
    img: assets/images/logo.jpg


plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-sitemap

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "Rakefile",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    ".gitignore",
    "CNAME",
  ]
