# main text of home
name: The Insight Group
bio: Professional mentorship at Northwestern University
home_bio: We know what NCA won't tell you. We are the ones plotting to take down NCS.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg
kellogg: assets/images/kellogg.jpg

# If you want to include your resume, set to true
# and specify source (external or local).

# url: https://koppl.in/indigo
url: http://theinsightgroup.org

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'



# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: NUInsightGroup
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
# github: mygithub
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: henry@insightgroup.org

authors:
  johndoe:
    name: John Doe
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/profile.jpg
    twitter: johndoe
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/james.jpg
    twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

events: true
apply: true
donate: true
about: true
blog: true
alumni: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "Rakefile",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    ".gitignore",
    "CNAME",
  ]
